### ISSUE TITLE
Use `noarch`

### ISSUE THREAD

**Issue by adibbley** [conda-forge/nvidia-gds-feedstock#1]
xref https://github.com/conda-forge/cuda-feedstock/issues/4

> As this package doesn't have any architecture dependency on its own, it would make sense to make this noarch. This would allow this package to be built once and reused on other architectures/OSes, which would simply the release process and cutdown on resource usage. For dependencies that are architecture/OS dependent, the right package would be pulled in. Raising to track evaluating this option

**Comment by jakirkham** [comment]
Thanks Alex! 🙏

Agree this is a good idea

Though given this is only building on `linux64` currently (and no other other OSes or architectures), it's probably lower priority than the other metapackages

https://github.com/conda-forge/nvidia-gds-feedstock/blob/93cf62c62e51660f11f1085544d56e108b4effb2/recipe/meta.yaml#L13

**Comment by adibbley** [comment]
This package was added for sbsa in 12.2, so maybe it is still worth making the switch now?

**Comment by jakirkham** [comment]
We skipped this for CUDA 12.2 as `linux_ppc64le` is not covered. More details in this thread ( https://github.com/conda-forge/nvidia-gds-feedstock/pull/3#discussion_r1431857777 )

**Comment by jakirkham** [comment]
Think we could do this by converting this to just a `linux` `noarch` package

It won't be possible to install on `linux_ppc64le` as the dependencies of this package are not available there

However this is ok as the error message will be clear to users and this already happens with other `noarch` packages

Will put something together for discussion

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
Included relevant changes in PR: https://github.com/conda-forge/nvidia-gds-feedstock/pull/12
